version: '3.8'


services:
  backend:
    build: .
    ports: '8000:8000'
  db:
    image: postgres9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress